package it.kirey.kfuture.entity;
// Generated 23-Sep-2016 13:33:51 by Hibernate Tools 5.1.0.Beta1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AmDictionary generated by hbm2java
 */
@Entity
@Table(name = "AM_DICTIONARY")
public class AmDictionary implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String genericName;
	private String defaultTranslation;
	@JsonManagedReference
	private List<AmResourceBundle> amResourceBundles;

	public AmDictionary() {
	}

	public AmDictionary(String genericName, String defaultTranslation) {
		this.genericName = genericName;
		this.defaultTranslation = defaultTranslation;
	}

	public AmDictionary(String genericName, String defaultTranslation, List<AmResourceBundle> amResourceBundles) {
		this.genericName = genericName;
		this.defaultTranslation = defaultTranslation;
		this.amResourceBundles = amResourceBundles;
	}

	@Id
	@Column(name = "GENERIC_NAME", unique = true, nullable = false)
	public String getGenericName() {
		return this.genericName;
	}

	public void setGenericName(String genericName) {
		this.genericName = genericName;
	}

	@Column(name = "DEFAULT_TRANSLATION", nullable = false, length = 4000)
	public String getDefaultTranslation() {
		return this.defaultTranslation;
	}

	public void setDefaultTranslation(String defaultTranslation) {
		this.defaultTranslation = defaultTranslation;
	}

	@OneToMany(mappedBy = "amDictionary")
	@LazyCollection(LazyCollectionOption.FALSE)
	public List<AmResourceBundle> getAmResourceBundles() {
		return this.amResourceBundles;
	}

	public void setAmResourceBundles(List<AmResourceBundle> amResourceBundles) {
		this.amResourceBundles = amResourceBundles;
	}

}
