package it.kirey.kfuture.entity;

//Generated Oct 3, 2016 9:37:02 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import it.kirey.kfuture.entity.AmUserAccounts;

/**
 * AmEmailTemplates generated by hbm2java
 */
@Entity
@Table(name = "AM_EMAIL_TEMPLATES", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class AmEmailTemplates implements java.io.Serializable {

	/**
	 * 
	 */
	private Integer id;
	private AmUserAccounts amUserAccountsByUtInsert;
	private AmUserAccounts amUserAccountsByUtUpdate;
	private String name;
	private byte[] template;
	private Date tsInsert;
	private Date tsUpdate;

	public AmEmailTemplates() {
	}

	public AmEmailTemplates(Integer id, AmUserAccounts amUserAccountsByUtInsert,
			AmUserAccounts amUserAccountsByUtUpdate, String name, byte[] template, Date tsInsert, Date tsUpdate) {
		this.id = id;
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
		this.name = name;
		this.template = template;
		this.tsInsert = tsInsert;
		this.tsUpdate = tsUpdate;
	}

	@Id
	@SequenceGenerator(name = "SEQ_AM_EMAIL_TEMPLATES_GEN", sequenceName = "SEQ_AM_EMAIL_TEMPLATES", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_AM_EMAIL_TEMPLATES_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UT_INSERT", nullable = false)
	public AmUserAccounts getAmUserAccountsByUtInsert() {
		return this.amUserAccountsByUtInsert;
	}

	public void setAmUserAccountsByUtInsert(AmUserAccounts amUserAccountsByUtInsert) {
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UT_UPDATE", nullable = false)
	public AmUserAccounts getAmUserAccountsByUtUpdate() {
		return this.amUserAccountsByUtUpdate;
	}

	public void setAmUserAccountsByUtUpdate(AmUserAccounts amUserAccountsByUtUpdate) {
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
	}

	@Column(name = "NAME", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TEMPLATE", nullable = false)
	public byte[] getTemplate() {
		return this.template;
	}

	public void setTemplate(byte[] template) {
		this.template = template;
	}

	@Column(name = "TS_INSERT", nullable = false)
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

}

