package it.kirey.kfuture.entity;
//Generated Oct 3, 2016 9:37:02 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import it.kirey.kfuture.entity.AmUserAccounts;

/**
* AmEmailConfigs generated by hbm2java
*/
@Entity
@Table(name = "AM_EMAIL_CONFIGS")
public class AmEmailConfigs implements java.io.Serializable {
	private static final long serialVersionUID = 347371099290275368L;
	
	private Integer id;
	private AmUserAccounts amUserAccountsByUtInsert;
	private AmUserAccounts amUserAccountsByUtUpdate;
	private String name;
	private String username;
	private String password;
	private String host;
	private Integer port;
	private Date tsInsert;
	private Date tsUpdate;

	public AmEmailConfigs() {
	}

	public AmEmailConfigs(Integer id, AmUserAccounts amUserAccountsByUtInsert, AmUserAccounts amUserAccountsByUtUpdate,
			String name, String username, String password, String host, Integer port, Date tsInsert, Date tsUpdate) {
		this.id = id;
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
		this.name = name;
		this.username = username;
		this.password = password;
		this.host = host;
		this.port = port;
		this.tsInsert = tsInsert;
		this.tsUpdate = tsUpdate;
	}

	@Id
	@SequenceGenerator(name = "SEQ_AM_EMAIL_CONFIGS_GEN", sequenceName = "SEQ_AM_EMAIL_CONFIGS", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_AM_EMAIL_CONFIGS_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UT_INSERT", nullable = false)
	public AmUserAccounts getAmUserAccountsByUtInsert() {
		return this.amUserAccountsByUtInsert;
	}

	public void setAmUserAccountsByUtInsert(AmUserAccounts amUserAccountsByUtInsert) {
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UT_UPDATE", nullable = false)
	public AmUserAccounts getAmUserAccountsByUtUpdate() {
		return this.amUserAccountsByUtUpdate;
	}

	public void setAmUserAccountsByUtUpdate(AmUserAccounts amUserAccountsByUtUpdate) {
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "USERNAME", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "HOST", nullable = false)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "PORT", nullable = false, precision = 10, scale = 0)
	public Integer getPort() {
		return this.port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}

	@Column(name = "TS_INSERT", nullable = false)
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

}
