package it.kirey.kfuture.entity;
// Generated Sep 22, 2016 3:50:04 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AmErrorLogs generated by hbm2java
 */
@Entity
@Table(name = "AM_ERROR_LOGS")
public class AmErrorLogs implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer id;

	// TODO
	/* @JsonBackReference */
	private AmUserAccounts amUserAccounts;
	private Date thrownDate;
	private String errorName;
	private String invokingUrl;
	private String message;

	@JsonManagedReference
	private AmErrorTraces amErrorTraces;

	public AmErrorLogs() {
	}

	public AmErrorLogs(Integer id, AmUserAccounts amUserAccounts, Date thrownDate, String errorName) {
		this.id = id;
		this.amUserAccounts = amUserAccounts;
		this.thrownDate = thrownDate;
		this.errorName = errorName;
	}

	public AmErrorLogs(Integer id, AmUserAccounts amUserAccounts, Date thrownDate, String errorName, String invokingUrl,
			String message, AmErrorTraces amErrorTraces) {
		this.id = id;
		this.amUserAccounts = amUserAccounts;
		this.thrownDate = thrownDate;
		this.errorName = errorName;
		this.invokingUrl = invokingUrl;
		this.message = message;
		this.amErrorTraces = amErrorTraces;
	}

	@Id
	@SequenceGenerator(name = "err_log_gen", sequenceName = "SEQ_AM_ERROR_LOGS", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "err_log_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "AM_USER_ACCOUNT", nullable = false)
	public AmUserAccounts getAmUserAccounts() {
		return this.amUserAccounts;
	}

	public void setAmUserAccounts(AmUserAccounts amUserAccounts) {
		this.amUserAccounts = amUserAccounts;
	}

	@Column(name = "THROWN_DATE", nullable = false, length = 7)
	public Date getThrownDate() {
		return this.thrownDate;
	}

	public void setThrownDate(Date thrownDate) {
		this.thrownDate = thrownDate;
	}

	@Column(name = "ERROR_NAME", nullable = false)
	public String getErrorName() {
		return this.errorName;
	}

	public void setErrorName(String errorName) {
		this.errorName = errorName;
	}

	@Column(name = "INVOKING_URL", length = 1000)
	public String getInvokingUrl() {
		return this.invokingUrl;
	}

	public void setInvokingUrl(String invokingUrl) {
		this.invokingUrl = invokingUrl;
	}

	@Column(name = "MESSAGE", length = 4000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@OneToOne(mappedBy = "amErrorLogs")
	public AmErrorTraces getAmErrorTraces() {
		return this.amErrorTraces;
	}

	public void setAmErrorTraces(AmErrorTraces amErrorTraces) {
		this.amErrorTraces = amErrorTraces;
	}
}
