package it.kirey.kfuture.entity;
// Generated Sep 22, 2016 3:00:20 PM by Hibernate Tools 5.1.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AmJobTraces generated by hbm2java
 */
@Entity
@Table(name = "AM_JOB_TRACES")
public class AmJobTraces implements java.io.Serializable {

	private static final long serialVersionUID = 5485820777266493176L;
	
	private Integer id;
	private AmTaskSchedulers amTaskSchedulers;
	private AmUserAccounts amUserAccountsByUtUpdate;
	private AmUserAccounts amUserAccountsByUtInsert;
	private String status;
	private Date tsInsert;
	private Date tsUpdate;

	public AmJobTraces() {
	}

	public AmJobTraces(Integer id, AmTaskSchedulers amTaskSchedulers, AmUserAccounts amUserAccountsByUtUpdate,
			AmUserAccounts amUserAccountsByUtInsert, Date tsInsert, Date tsUpdate) {
		this.id = id;
		this.amTaskSchedulers = amTaskSchedulers;
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
		this.tsInsert = tsInsert;
		this.tsUpdate = tsUpdate;
	}

	public AmJobTraces(Integer id, AmTaskSchedulers amTaskSchedulers, AmUserAccounts amUserAccountsByUtUpdate,
			AmUserAccounts amUserAccountsByUtInsert, String status, Date tsInsert, Date tsUpdate) {
		this.id = id;
		this.amTaskSchedulers = amTaskSchedulers;
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
		this.status = status;
		this.tsInsert = tsInsert;
		this.tsUpdate = tsUpdate;
	}

	@Id
	@SequenceGenerator(name = "SEQ_AM_JOB_TRACES_GEN", sequenceName = "SEQ_AM_JOB_TRACES", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_AM_JOB_TRACES_GEN")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AM_TASK_SCHEDULER", nullable = false)
	public AmTaskSchedulers getAmTaskSchedulers() {
		return this.amTaskSchedulers;
	}

	public void setAmTaskSchedulers(AmTaskSchedulers amTaskSchedulers) {
		this.amTaskSchedulers = amTaskSchedulers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UT_UPDATE", nullable = false)
	public AmUserAccounts getAmUserAccountsByUtUpdate() {
		return this.amUserAccountsByUtUpdate;
	}

	public void setAmUserAccountsByUtUpdate(AmUserAccounts amUserAccountsByUtUpdate) {
		this.amUserAccountsByUtUpdate = amUserAccountsByUtUpdate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UT_INSERT", nullable = false)
	public AmUserAccounts getAmUserAccountsByUtInsert() {
		return this.amUserAccountsByUtInsert;
	}

	public void setAmUserAccountsByUtInsert(AmUserAccounts amUserAccountsByUtInsert) {
		this.amUserAccountsByUtInsert = amUserAccountsByUtInsert;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TS_INSERT", nullable = false)
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

}
