package it.kirey.kfuture.entity;
// Generated 03-Oct-2016 09:46:32 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;


/**
 * AmReportBookingParameters generated by hbm2java
 */
@Entity
@Table(name = "AM_REPORT_BOOKING_PARAMETERS", uniqueConstraints = @UniqueConstraint(columnNames = { "AM_REPORT_BOOKING",
		"AM_REPORT_PARAMETER" }))
public class AmReportBookingParameters implements java.io.Serializable {	
	private static final long serialVersionUID = 1L;
	private Integer id;
	
	@JsonBackReference(value="booking_parameters")
	private AmReportBookings amReportBookings;
	
	@JsonBackReference
	private AmReportParameters amReportParameters;
	private String value;

	public AmReportBookingParameters() {
	}

	public AmReportBookingParameters(Integer id) {
		this.id = id;
	}

	public AmReportBookingParameters(Integer id, AmReportBookings amReportBookings,
			AmReportParameters amReportParameters, String value) {
		this.id = id;
		this.amReportBookings = amReportBookings;
		this.amReportParameters = amReportParameters;
		this.value = value;
	}

	@Id
	@SequenceGenerator(name = "reportparamvalues_gen", sequenceName = "SEQ_AM_REPORT_BOOKING_PARAM", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "reportparamvalues_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AM_REPORT_BOOKING")
	public AmReportBookings getAmReportBookings() {
		return this.amReportBookings;
	}

	public void setAmReportBookings(AmReportBookings amReportBookings) {
		this.amReportBookings = amReportBookings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AM_REPORT_PARAMETER")
	public AmReportParameters getAmReportParameters() {
		return this.amReportParameters;
	}

	public void setAmReportParameters(AmReportParameters amReportParameters) {
		this.amReportParameters = amReportParameters;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
