package it.kirey.kfuture.entity;
// Generated 03-Oct-2016 09:46:32 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AmReportBlobs generated by hbm2java
 */
@Entity
@Table(name = "AM_REPORT_BLOBS")
public class AmReportBlobs implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer amReport;
	
	@JsonBackReference(value = "blob_file")
	private AmReports amReports;
	
	
	private byte[] fileBlob;
	private Long pfile;

	public AmReportBlobs() {
	}

	public AmReportBlobs(AmReports amReports, byte[] fileBlob) {
		this.amReports = amReports;
		this.fileBlob = fileBlob;
	}

	public AmReportBlobs(AmReports amReports, byte[] fileBlob, Long pfile) {
		this.amReports = amReports;
		this.fileBlob = fileBlob;
		this.pfile = pfile;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "amReports"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "AM_REPORT", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getAmReport() {
		return this.amReport;
	}

	public void setAmReport(Integer amReport) {
		this.amReport = amReport;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public AmReports getAmReports() {
		return this.amReports;
	}

	public void setAmReports(AmReports amReports) {
		this.amReports = amReports;
	}

	@JsonIgnore
	@Lob
	@Column(name = "FILE_BLOB", nullable = false)
	public byte[] getFileBlob() {
		return this.fileBlob;
	}
	
	@JsonProperty
	public void setFileBlob(byte[] fileBlob) {
		this.fileBlob = fileBlob;
	}

	@Column(name = "PFILE", precision = 10, scale = 0)
	public Long getPfile() {
		return this.pfile;
	}

	public void setPfile(Long pfile) {
		this.pfile = pfile;
	}

}
