package it.kirey.kfuture.entity;
// Generated Oct 13, 2016 4:17:24 PM by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * AmUrlRoutes generated by hbm2java
 */
@Entity
@Table(name = "AM_URL_ROUTES")
public class AmUrlRoutes implements java.io.Serializable {

	private Integer id;
	private String url;
	private Integer utInsert;
	private Date tsInsert;
	private Integer utUpdate;
	private Date tsUpdate;
	@JsonBackReference
	private List<AmApplicationRoles> amApplicationRoleses = new ArrayList<AmApplicationRoles>(0);

	public AmUrlRoutes() {
	}

	public AmUrlRoutes(Integer id, String url, Integer utInsert, Date tsInsert, Integer utUpdate, Date tsUpdate) {
		this.id = id;
		this.url = url;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
	}

	public AmUrlRoutes(Integer id, String url, Integer utInsert, Date tsInsert, Integer utUpdate, Date tsUpdate,
			List<AmApplicationRoles> amApplicationRoleses) {
		this.id = id;
		this.url = url;
		this.utInsert = utInsert;
		this.tsInsert = tsInsert;
		this.utUpdate = utUpdate;
		this.tsUpdate = tsUpdate;
		this.amApplicationRoleses = amApplicationRoleses;
	}

	@Id
	@SequenceGenerator(name = "urlRoutes_gen", sequenceName = "SEQ_AM_URL_ROUTES", allocationSize = 1, initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "urlRoutes_gen")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "URL", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "UT_INSERT", nullable = false, precision = 10, scale = 0)
	public Integer getUtInsert() {
		return this.utInsert;
	}

	public void setUtInsert(Integer utInsert) {
		this.utInsert = utInsert;
	}

	@Column(name = "TS_INSERT", nullable = false)
	public Date getTsInsert() {
		return this.tsInsert;
	}

	public void setTsInsert(Date tsInsert) {
		this.tsInsert = tsInsert;
	}

	@Column(name = "UT_UPDATE", nullable = false, precision = 10, scale = 0)
	public Integer getUtUpdate() {
		return this.utUpdate;
	}

	public void setUtUpdate(Integer utUpdate) {
		this.utUpdate = utUpdate;
	}

	@Column(name = "TS_UPDATE", nullable = false)
	public Date getTsUpdate() {
		return this.tsUpdate;
	}

	public void setTsUpdate(Date tsUpdate) {
		this.tsUpdate = tsUpdate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "AM_ROLE_ROUTES", joinColumns = {
			@JoinColumn(name = "AM_ROUTE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "AM_APPLICATION_ROLE", nullable = false, updatable = false) })
	public List<AmApplicationRoles> getAmApplicationRoleses() {
		return this.amApplicationRoleses;
	}

	public void setAmApplicationRoleses(List<AmApplicationRoles> amApplicationRoleses) {
		this.amApplicationRoleses = amApplicationRoleses;
	}

}