// default package
// Generated 26-Sep-2016 09:55:14 by Hibernate Tools 5.2.0.Beta1
package it.kirey.kfuture.entity;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestClients generated by hbm2java
 */
@Entity
@Table(name = "TEST_CLIENTS")
public class TestClients implements java.io.Serializable {

	private int id;
	private String lastName;
	private String email;
	private String firstName;
	private Date dateBirth;
	private Character gender;
	private String country;
	private String address;
	private String phone;

	public TestClients() {
	}

	public TestClients(int id, String lastName, String email, String firstName, Date dateBirth, String phone) {
		this.id = id;
		this.lastName = lastName;
		this.email = email;
		this.firstName = firstName;
		this.dateBirth = dateBirth;
		this.phone = phone;
	}

	public TestClients(int id, String lastName, String email, String firstName, Date dateBirth, Character gender,
			String country, String address, String phone) {
		this.id = id;
		this.lastName = lastName;
		this.email = email;
		this.firstName = firstName;
		this.dateBirth = dateBirth;
		this.gender = gender;
		this.country = country;
		this.address = address;
		this.phone = phone;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "DATE_BIRTH", nullable = false, length = 7)
	public Date getDateBirth() {
		return this.dateBirth;
	}

	public void setDateBirth(Date dateBirth) {
		this.dateBirth = dateBirth;
	}

	@Column(name = "GENDER", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "COUNTRY", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "ADDRESS", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PHONE", nullable = false, length = 12)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
